import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScoreBar } from "@/components/dashboard/score-bar";
import { ScoreRadarChart } from "@/components/dashboard/score-radar-chart";
import { scoreColor } from "@/lib/utils";
import type { ResumeAnalysis } from "@/types";

export function ResumeAnalysisPanel({ analysis }: { analysis: ResumeAnalysis }) {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Resume score</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-6 lg:grid-cols-2">
          <div className="space-y-5">
            <div className="flex items-baseline gap-2">
              <span className={`text-4xl font-bold ${scoreColor(analysis.overall_score)}`}>
                {analysis.overall_score}
              </span>
              <span className="text-sm text-muted-foreground">/ 100 overall</span>
            </div>

            <div className="space-y-4">
              <ScoreBar label="Skills" score={analysis.skills_score} />
              <ScoreBar label="Experience" score={analysis.experience_score} />
              <ScoreBar label="Projects" score={analysis.projects_score} />
              <ScoreBar label="Education" score={analysis.education_score} />
              <ScoreBar label="Structure" score={analysis.structure_score} />
              <ScoreBar label="Achievements" score={analysis.achievements_score} />
              <ScoreBar label="Keywords" score={analysis.keywords_score} />
              <ScoreBar label="Job relevance" score={analysis.job_relevance_score} />
            </div>
          </div>
          <div className="flex items-center justify-center">
            <ScoreRadarChart analysis={analysis} />
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-4 sm:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="text-emerald-600 dark:text-emerald-400">Strengths</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              {(analysis.strengths ?? []).map((s, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-emerald-600 dark:text-emerald-400">✓</span>
                  {s}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-amber-600 dark:text-amber-400">Weaknesses</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              {(analysis.weaknesses ?? []).map((w, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-amber-600 dark:text-amber-400">!</span>
                  {w}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recommendations</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2 text-sm">
            {(analysis.recommendations ?? []).map((r, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-primary">•</span>
                {r}
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <p className="text-xs text-muted-foreground">
        Generated by {analysis.ai_provider_used === "mock" ? "the mock AI provider (no API key configured)" : analysis.ai_provider_used} — AI-generated analysis, not a guaranteed outcome.
      </p>
    </div>
  );
}
